require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 78
# Max: 120

Gemspec/RequireMFA:
  Enabled: false

Layout/LineContinuationLeadingSpace:
  EnforcedStyle: leading

Style/BlockComments:
  Enabled: false
