require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Naming/FileName:
  Exclude:
    - lib/pr-readline.rb

Gemspec/RequireMFA:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/LineLength:
  Max: 80
# Max: 120

Layout/LineContinuationLeadingSpace:
  EnforcedStyle: leading

Style/BlockComments:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
